baseURL = 'https://blaaskaak.nl'
languageCode = 'nl-NL'
title = 'Blaaskaak'
disableKinds = ['rss', 'taxonomy', 'term']

[params]
  shortDescription = "Blaaskaak – Party Rave Band"
  description = "Blaaskaak is a high-energy party rave band known for electrifying performances and unforgettable music. Join the rave and experience the ultimate party vibe!"
  shareImage = "/media/standby.jpg"
  favicon = "/media/logo-slechte-kwali.png"
