#!/usr/bin/env bash

scriptfolder="$(dirname $(realpath $0))"
venvfolder="$scriptfolder/.venv"

if [ ! -d "$venvfolder" ]; then
  python3 -m venv "$venvfolder"
  source "$venvfolder/bin/activate"
  pip install -r "$scriptfolder/requirements.txt"
fi

source "$venvfolder/bin/activate"

python3 "$scriptfolder/ical2json.py" "$scriptfolder/../data/events.json"
