#!/usr/bin/env bash

function killchilds(){
    kill $(jobs -p -r)
}

trap killchilds INT

python3 -m http.server --directory ${1:public} &
(while true; do make site >/dev/null; sleep 1; done) &

wait
